#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse

parser = argparse.ArgumentParser(description = "To add the D to Viruses line \
    to kraken report generated by Diamond, making it compatible with Pavian")

parser.add_argument("-i", "--kraken_report", help="Kraken taxonomic report from Diamond",
    required=True)
parser.add_argument("-o", "--output_parsable", help="output usable by Pavian",
    required=True)

args = parser.parse_args()

report_file = args.kraken_report
output_file = args.output_parsable

rep_handle = open(report_file, 'r')
save_handle = open(output_file, 'w')

for line in rep_handle:
    # 59.31	7732	7732	U	0	unclassified

    lst_line = line.split('\t')
#    print(lst_line)
    if lst_line[4]=="10239":
        new_line=lst_line[0]+'\t'+lst_line[1]+'\t'+lst_line[2]+'\t'+"D"+'\t'+ \
        lst_line[4]+'\t'+lst_line[5]
        print(new_line)
        save_handle.write(new_line)
    else:
        save_handle.write(line)

rep_handle.close()
save_handle.close()
